// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.184
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MultiEdit
{
    static class Vsix
    {
        public const string Id = "MultiEdit..c6fb8e57-fde0-4987-8e7a-5ca9b4beddcb";
        public const string Name = "Multi Select Mode";
        public const string Description = @"Simultaneously edit in more than one location in the editor

If you've ever ran into a case where you wanted to quickly change variable names or multiple loop conditions - you can use this extension to set virtual carets that all behave the same.";
        public const string Language = "en-US";
        public const string Version = "1.8";
        public const string Author = "Ala Shiban";
        public const string Tags = "cursor, caret, typing";
    }
}
